Models/Project.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Task_Management_System.Models
{
    public class Project
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public ICollection<Task_Management_System.Models.Task> Tasks;
        public List<User> Users { get; } = new();
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Task_Management_System.Models;
using Task_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
namespace Task_Management_System.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly AppDbContext _context;

        public ProjectsController(AppDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public ActionResult Index()
        {
            var cUser = _context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            ViewBag.CurrUser = cUser;
            var projects = _context.Projects.ToList();
            ViewBag.Projects = projects;
            return View(projects);
        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            var projectTasks = _context.Tasks.Where(task => task.ProjectId == id);
            var project = _context.Projects.First(p => p.Id == id);
            ViewBag.Project = project;
            ViewBag.Tasks =  projectTasks;
            return View(project);
        }
        [HttpGet]
        public IActionResult Edit(string? id)
        {
            var project = _context.Projects.FirstOrDefault(p => p.Id == id);
            var currentUser = _context.Users.FirstOrDefault(user => user.Email == User.Identity.Name);
            try
            {
                currentUser.Projects.Add(project);
                // _context.Projects.Update(project);
                _context.SaveChanges();
                ViewBag.Message = "Data Insert Successfully";
            }
            catch (Exception ex)
            {
                return Redirect("/");
            }
            return Redirect("/Users/Details/");
        }
        [HttpPost]
        public IActionResult Edit(Project project)
        {
            var currentUser = _context.Users.FirstOrDefault(user => user.Email == User.Identity.Name);
            if (!_context.Users.FirstOrDefault(u => u.Id == currentUser.Id).Projects.Exists(p => p.Id == project.Id))
            {
                currentUser.Projects.Add(project);
                // _context.Projects.Update(project);
                _context.SaveChanges();
                ViewBag.Message = "Data Insert Successfully";
            }

            return Redirect("/Users/Details/");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ViewResult Create(Project project)
        {
            string currentUserId = _context.Users.FirstOrDefault(user => user.Email == User.Identity.Name).Id;
            _context.Projects.Add(project);
            _context.SaveChanges();
            ViewBag.Message = "Data Insert Successfully";
            return View();
        }
    }
}

Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Task_Management_System.Models;
using Task_Management_System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Task_Management_System.Controllers
{
    public class TasksController : Controller
    {
        public string Email;
        private readonly AppDbContext _context;

        public TasksController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var tasks = _context.Tasks.ToList();
            ViewBag.Tasks = tasks;
            return View(tasks);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            var task = _context.Tasks.Where(x => x.Id == id);
            ViewBag.Task = task.ToList().ElementAt(0);
            return View(task);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Create(Models.Task task, string projectId, string email)
        {
            try
            {
                task.AssigneeId = _context.Users.FirstOrDefault(user => user.Email == email).Id;
                task.ProjectId = projectId;
                _context.Tasks.Add(task);
                _context.SaveChanges();
                ViewBag.Message = "Data Insert Successfully";
                return View(task);
            }
            catch (Exception ex)
            {
                return View(ex.Message); // An error occured
            }
        }

        [HttpGet]
        public IActionResult Edit(int? id, string projectId)
        {
            var task = _context.Tasks.FirstOrDefault(task => task.Id == id);
            task.AssigneeId = _context.Users.FirstOrDefault(user => user.Email == User.Identity.Name).Id;
            task.ProjectId = projectId;
            return View(task);
        }
        [HttpPost, ActionName("Edit"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Models.Task task)
        {
            if(task == null){
                return NotFound();
            }
            _context.Update(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Task_Management_System.Data;
using Microsoft.EntityFrameworkCore;

namespace Task_Management_System.Controllers;
public class UsersController : Controller
{
    private readonly AppDbContext _context;

    public UsersController(AppDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public ActionResult Index()
    {
        var users = _context.Users.ToList();
        ViewBag.User = _context.Users;
        return View();
    }
    [HttpGet]
    public IActionResult Details()
    {
        var user = _context.Projects.Where(p =>
            p.Users.FirstOrDefault(u => u.Email == User.Identity.Name).Email == User.Identity.Name);
        ViewBag.Tarifs = user;
        return View();
    }

    [HttpGet]
    public IActionResult Destroy(string? id)
    {
        var project = _context.Projects.Include(p => p.Users).Single(u => u.Id == id);
        var currentUser = _context.Users.Single(user => user.Email == User.Identity.Name);
        project.Users.Remove(project.Users.Where(u => u.Id == currentUser.Id).FirstOrDefault());
        _context.SaveChanges();


//         var groupToUpdate = _userGroupsContext.Groups.Include(g => g.UserGroups).Single(u => u.Id == userVm.groupsIds[0]);
// var userToUpdate = _userGroupsContext.Users.Single(u => u.Id == userVm.user.Id);

// groupToUpdate.UserGroups.Remove(groupToUpdate.UserGroups.Where(ugu => ugu.UserId == userToUpdate.Id).FirstOrDefault());
// _userGroupsContext.SaveChanges();
        return Redirect("/Users/Details/");
    }
}

Views/Projects/Create.cshtml
@model Task_Management_System.Models.Project
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Create</title>
    <link rel="stylesheet" href="~/css/projects_create.css">
</head>
<body>

    @if (ViewBag.Message != null)
    {
        <div role="alert">
            @ViewBag.Message
        </div>
    }

    @using (Html.BeginForm("Create", "Projects", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <h1>Создать новый тариф</h1>
            <hr/>

            @Html.ValidationSummary(true)

            <div class="form-group">
                <label for="Title">Название</label>
                @Html.EditorFor(model => model.Title)
            </div>

            <div class="form-group">
                <label for="Description">Цена</label>
                @Html.EditorFor(model => model.Description)
            </div>

            <div class="form-group">
                <input type="submit" value="Создать" />
            </div>

            <div class="actions">
                <a href="@Url.Action("Index", "Projects")" class="btn-back">Назад к списку</a>
            </div>
        </div>
    }
</body>
</html>

Views/Projects/Details.cshtml
@model Task_Management_System.Models.Project

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/projects_details.css" />
</head>
<body>
    <div class="container">
        <h1>@Model.Title Details</h1>
        <div class="project-details">
            <h2>@Model.Title</h2>
            <p>@Model.Description</p>
        </div>
        <div class="actions">
            <a href="@Url.Action("Index", "Projects")" class="btn-back">Back to List</a>
            <a href="@Url.Action("Create", "Tasks", new { projectId = Model.Id })" class="btn-back">Add task</a>
        </div>
    </div>
    <div class="tasks-container">
        @foreach (var task in @ViewBag.Tasks)
        {
            <div class='item-container'>
                <h3>@task.Title</h3>
                <h4>@task.Description</h4>
                <h3>@task.Progress</h3>
                <h2>@task.Assignee</h2>
                <div class="actions">
                    <a href="@Url.Action("Edit", "Projects")" class="btn-back">Back to List</a>
                </div>
            </div>
        }
    </div>
</body>
</html>

Views/Projects/Edit.cshtml
@using Task_Management_System.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Update</title>
    <link rel="stylesheet" href="~/css/projects_edit.css">
</head>
<body>
    <div class="container">
        <h1>Edit</h1>
        @if (ViewBag.Message != null)
        {
            <div role="alert">
                @ViewBag.Message
            </div>
        }






        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div>
                @Html.ValidationSummary(true)

                @* <div class="form-group"> *@
                @*     <div> *@
                @*         <p>Title</p> *@
                @*         <input asp-for="Title"/> *@
                @*     </div> *@
                @* </div> *@
                @* *@
                @* <div class="form-group"> *@
                @*     <div> *@
                @*         <p>Description</p> *@
                @*         @Html.TextBox(Model.Title, ) *@
                @*     </div> *@
                @* </div> *@

                <div class="form-group">
                    <div>
                        <input type="submit" value="Update" />
                    </div>
                </div>

            </div>
        }
        <div class="actions">
            <a href="@Url.Action("Index", "Projects")" class="btn-back">Back to List</a>
        </div>
    </div>
</body>
</html>

Views/Projects/Index.cshtml
@using Task_Management_System.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/projects_index.css">
</head>
<body>
    <header>
    <nav>
        <div class="logo">
            <a class="logo-text">Zhest</a>
        </div>
        <div class="nav-links">
                <a class="nav-link-element" href="@Url.Action("Details", "Users")">Подключенные тарифы</a>

            @if (ViewBag.CurrUser != null && ViewBag.CurrUser.Role.ToString() == "Admin")
            {
                <a class="nav-link-element" href="@Url.Action("Create", "Projects")">Создать тариф</a>
            }
         </div>
    </nav>
    </header>
    <main>
    <div class="container">
            <h1>Тарифы</h1>

            @if (ViewBag.Message != null)
            {
                <div role="alert">
                    @ViewBag.Message
                </div>
            }

                <div class="project-list">
                @foreach (var item in Model)
                {
                    <div class="card">
                        <h2 class="card-title">@item.Title</h2>
                        <p class="card-description">@item.Description</p>
                        <a class="card-button" href="@Url.Action("Edit", "Projects", new { id = item.Id, userId = @User.Identity.Name })">Подключить</a>
                    </div>
                }
            </div>
        </div>
    </main>
</body>
</html>